stages:
  - name: buildTTGateway
    transformations:
      - rto-dist

transformations:
  - name: rto-dist
    service: rto-test-service
    command: discover
    parameters:
      classes: 5bb36ef7b9d82100066314e0

assessments:
  - name: rto-run
    service: rto-test-service
    command: execute
    dependsOn:
      - alias: testclasses
        ref: p://this/transformations/rto-dist/testClasses
    parameters:
      classes: 5bb36ef7b9d82100066314e0
      testOrder: "@testclasses"
 
qualityGates: 
  - strategy: auto
    policies:
      - name: PassedTestRate
        interpretation: threshold-
        actualValue: passedRate
        setPoint: 1
        assessmentRef: p://this/assessments/rto-run
