stages:
  - name: buildTTGateway
    transformations:
      - rto-dist
      - rto-optimize-testtime
      - rto-optimize-failedfirst

transformations:

  - name: rto-dist
    service: rto-test-service
    command: discover
    parameters:
      classes: 5bb36ef7b9d82100066314e0

  - name: rto-optimize-testtime
    service: rto-optimize-testexecutiontimeprioritization-service
    command: optimize
    dependsOn:
      - alias: testclasses
        ref: p://this/transformations/rto-dist/testClasses
      - alias: model
        ref: p://this/model/id
    parameters:
      testRef: "@testclasses"
      modelId: "@model"
      
  - name: rto-optimize-failedfirst
    service: rto-optimize-failedfirstprioritization-service
    command: optimize
    dependsOn:
      - alias: testclasses
        ref: p://this/transformations/rto-optimize-testtime/testRef
      - alias: model
        ref: p://this/model/id
    parameters:
      testRef: "@testclasses"
      modelId: "@model"

assessments:
  - name: rto-run
    service: rto-test-service
    command: execute
    dependsOn:
      - alias: testclasses
        ref: p://this/transformations/rto-optimize-failedfirst/testRef
    parameters:
      classes: 5bb36ef7b9d82100066314e0
      testOrder: "@testclasses"
      
probes:
  - name: rto-probe
    service: rto-test-history-probe-service
    command: probe
    dependsOn:
      - alias: testreport
        ref: p://this/assessments/rto-run/testReport
      - alias: model
        ref: p://this/model/id
    parameters:
      testReport: "@testreport"
      modelId: "@model"
 
qualityGates: 
  - strategy: auto
    policies:
      - name: PassedTestRate
        interpretation: threshold-
        actualValue: passedRate
        setPoint: 1
        assessmentRef: p://this/assessments/rto-run
